services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=clientepedidos'
      - 'MYSQL_PASSWORD=1234senha'
      - 'MYSQL_ROOT_PASSWORD=1234senha'
      - 'MYSQL_USER=myapipedidos'
    ports:
      - '4000:3306'
  